export const ROLES_SELECT: string = '+SMAmB-8XRT7r-rbdn8v-,Pw8Ub'
export const ROLES_PREV: string = '2jex,9-Z9C|FB-EbTaT7-ipvWDr'
export const ROLES_INDEX: string = '~JBH8z-TMZ|xv-b46r8r-jvaLYp'
export const ROLES_INDEX_MODAL: string = '*|xfny-z5MvhT-wt9LMM-by3Fd4'
export const ROLES_NEXT: string = 'PAp/m2-J3VsWb-ghQQ:2-nq5mea'