export const TIMEZONE_SELECT: string = 'UnDmPi-SXF88C-Psqmc[-C3t?i6'
export const TIMEZONE_PREV: string = 'KMjuPK-qiT9k]-3iaX2(-5KAXZt'
export const TIMEZONE_INDEX: string = 'QPg2UU-2wTNBE-Pi.wf;-j6Umd3'
export const TIMEZONE_INDEX_MODAL: string = 'xAddXS-ZW2g~K-97mGDr-nNh3m*'
export const TIMEZONE_NEXT: string = 'wW2v9T-Piz3bx-qVwG[j-SB+2yX'