export const VOICE_GIVE: string = 'JFK~B:-3526bd-mgGrBv-zDJzCF'
export const VOICE_GIVE_MODAL: string = 'gdcWSG-XF/C.b-rPqus9-U22gG4'
export const VOICE_GIVE_MODAL_VALUE_FROM: string = 'bpinUJ-rMY5|X-jdSk3A-.6fHC4'
export const VOICE_GIVE_MODAL_VALUE_TO: string = 'S3Dh6s-s7L^Be-MVdvA"-k4pGbU'
export const VOICE_GIVE_RESET: string = 'rfTzFV-kT3y3N-:CMn2k-Ak5$gM'