export const RANK: string = '4MHz6F-emakR<-g^BcH4-8CeNEU'
export const RANK_AFTER: string = 'B<VkPQ-yhMK5V-h9N+2L-wMrUd5'
export const USERS: string = 'e*y2V5-tG9eBW-/PxQp2-vKGCpK'
export const USERS_AFTER: string = 'JPS98S-q)V~Zj-8WtCq3-tmdnqC'
export const USERS_PREV: string = '8"55Ak-fBUcjf-MKCG:e-qMde5u'
export const USERS_INDEX: string = 'HctJKn-A*W44J-i5prHr-Xn6dD['
export const USERS_INDEX_MODAL: string = '8bf;3F-FjQ5Jd-kmkYr5-UKw!Rt'
export const USERS_NEXT: string = 'DiVZ2H-qA5ki8-Z<*Ugg-ty2CPA'
