export const CLAN_CHANNEL_UR_SELECT = 'Lbc3GL-rdW3tb-{QJ23%-FvQnbN'
export const CLAN_CHANNEL_UR_RIGHT_SELECT = 'hLQTzW-c*myb(-7ND5n8-a4zBHU'
export const CLAN_CHANNEL_UR_PERMISSION_SELECT = 'nQ}MsE-yJvxMR-7{x6CF-4EBv9A'