export const CLAN_CHANNEL_RIGHTS_SELECT = 'ekhcBG-N4MUAy-n8jut9-s6FqSX'
export const CLAN_CHANNEL_RIGHTS_ADD_SELECT = 'h7nRGP-a5GjBc-MBKfSV-9PgZn6'
export const CLAN_CHANNEL_RIGHTS_REMOVE_SELECT = 'YYD6Fw-S8vN2T-uMz6Wc-GAfirx'
