export const TOP_PREV: string = 'NjzM^R-$3he2B-mM3F4E-eZdjhy'
export const TOP_INDEX: string  = '5JfM2f-3EvWKN-ir%nLy-Uj4?Vw'
export const TOP_INDEX_MODAL: string = 'ZeV,3h-iBMrXq-UG9D23-RnzVN#'
export const TOP_NEXT: string = 'KkMGjk-92:puc-8Df2uG-W/rswD'
export const TOP_REFRESH: string = '4FxSyP-bJ4qm4-fSL`wh-5JR/pw'