export const MUN_CHANNEL: string = 'PRG@wL-P6qp.Z-a8awK9-JsxZ3E'
export const MUN_ROLES: string = 'vjCs6n-Be#`BH-vFCGF4-2W4SjR'
export const MUN_SEND: string = '5wKcHq-;pS5aK-NQgVX`-37jjMv'
export const MUN_EDIT: string = '9uG?Bw-78THUJ-wvkY3v-G|YveR'
export const MUN_EDIT_MODAL: string = 'cCtq)4-FnA6e7-6EbuHu-TLGT$Y'
export const MUN_EDIT_MODAL_TITLE: string = 'UwZX25-7bP^jd-D[ABqK-znx7YB'
export const MUN_EDIT_MODAL_DESCRIPTION: string = 'cVNFnq-eMsQ,5-2CzVK6-5amt^k'