export const QA_ACTION: string = 'J"Shqk-gh>dZY-H6Nvi5-N3hrL2'
export const QA_REPLY: string = '>M4kWj-%UDGHq-TjepSb-42yv3u'
export const QA_EDIT: string = 'kEVpEx-wUVqED-rEr@87-v7+Kn5'
export const QA_RESOLVE: string = 'NYHDR~-jh|Vb9-ijbc3P-t7v3Ks'
export const QA_DELETE: string = '9B4=6[-tsRmgT-W8tDgE-PiLhNQ'